# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirBnbApp' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'AirBnbAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AirBnbApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AirBnbApp-tvOS

  target 'AirBnbApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
